# Generated by Django 2.2.18 on 2021-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhpbbAlbum',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_filename', models.CharField(max_length=255)),
                ('pic_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('pic_title', models.CharField(max_length=255)),
                ('pic_username', models.CharField(blank=True, max_length=32, null=True)),
                ('pic_cat_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'phpbb_album',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhpbbAlbumCat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(max_length=255)),
                ('cat_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phpbb_album_cat',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
