# Generated by Django 2.2.18 on 2021-03-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210313_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='r_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='r_owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
